import { ref } from "vue";
import { auth } from "@/firebase/firebase.js";
import {
  signInWithCustomToken, // Changed from signInWithEmailAndPassword
  signOut,
  onAuthStateChanged
} from "firebase/auth";

const currentUser = ref(null);
const authReady = ref(false);

let listenerStarted = false;
function ensureListener() {
  if (listenerStarted) return;
  listenerStarted = true;
  onAuthStateChanged(auth, (user) => {
    currentUser.value = user;
    authReady.value = true;
  });
}

export function useAuth() {
  ensureListener();

  async function login(email, password) {
    // 1. Send credentials to your own backend
    const response = await fetch("http://localhost:3000/api/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password })
    });

    const data = await response.json();

    if (!data.success) {
      throw new Error(data.error);
    }

    // 2. Log into the Firebase Client SDK using the Custom Token generated by your server.
    // This step is CRITICAL to keep your Firestore SDK CRUD functions working!
    const cred = await signInWithCustomToken(auth, data.customToken);
    return cred.user;
  }

  async function logout() {
    await signOut(auth);
  }

  async function getToken() {
    if (!currentUser.value) throw new Error("Not authenticated");
    return currentUser.value.getIdToken();
  }

  return { currentUser, authReady, login, logout, getToken };
}